### ISSUE TITLE
add reaxon

### ISSUE THREAD

**Issue by LXSMNSYC** [redex/data#128]
```json
"lxsmnsyc/reaxon": {
  "repository": "github:lxsmnsyc/reaxon",
  "category": "library",
  "platforms": ["any"],
  "keywords": ["reasonml", "reactive-extensions", "rx", "reactive-streams"]
}
```

**Comment by glennsl** [comment]
Thanks! But before I add it I'd like to see the readme fleshed out a little bit. Specifically the installation section, an example and a slightly more elaborate description would be nice.

**Comment by LXSMNSYC** [comment]
Certainly! The library is completely experimental yet, so I'll let you know if the API is final and the README has been setup.
