### ISSUE TITLE
add re-use

### ISSUE THREAD

**Issue by LXSMNSYC** [redex/data#130]
```json
"@lxsmnsyc/re-use": {
  "category": "library",
  "platforms": ["browser"],
  "keywords": ["react", "state management"]
}
```

**Comment by glennsl** [comment]
Thanks!  :+1:

**Comment by LXSMNSYC** [comment]
ohh, I forgot to edit the keywords. It should've been ["react", "hooks"] :/ I'm sorry, my mistake.

**Comment by glennsl** [comment]
Don't worry, I edited it from that to "state management" (thinking for a moment this was a PR) since "state management" is an established category while "hooks" isn't. We probably will have a "hooks"  category eventually, but right it would only be this, which is a bit thin for a new one.
