### ISSUE TITLE
Add bs-rest-api

### ISSUE THREAD

**Issue by digitake** [redex/data#146]
"@digitake/bs-rest-api": {
  "category": "library",
  "platforms": ["browser", "node"],
  "keywords": ["data fetching", "data serialization", "json", "utilities"]
}

**Comment by glennsl** [comment]
Added. Thanks! Also, cool project and nice readme!

**Comment by digitake** [comment]
Thanks! It is inspired by your `bs-json` and `Django Rest Framework`.
