### ISSUE TITLE
Submitting a package: bs-compression

### ISSUE THREAD

**Issue by viebel** [redex/data#17]
"bs-compression": {
 "repository": "github:viebel/bs-compression",
  "category": "binding" ,
  "platforms": ["node" ],
  "keywords": ["compression", "nodejs", "middleware"]
}

**Comment by glennsl** [comment]
Thanks! The readme is quite severely inadequate though. Have a look at https://redex.github.io/publish for more information on what a good readme should, and let me know when you've addressed it :)

**Comment by viebel** [comment]
Readme improved.
Please let me know if it is informative enough or what other information should be included.

**Comment by glennsl** [comment]
Looks good! But you need to publish it for it to get picked up.

**Comment by viebel** [comment]
What does it mean to publish a package? Do you mean `npm publish`?

**Comment by glennsl** [comment]
yeah, just bump the version and run `npm publish`.

**Comment by viebel** [comment]
done

**Comment by glennsl** [comment]
Thanks!
