### ISSUE TITLE
Submitting a package: bs-react-ga

### ISSUE THREAD

**Issue by viebel** [redex/data#18]
"bs-react-ga": {
 "repository": "github:viebel/bs-react-ga",
  "category": "binding" ,
  "platforms": ["browser"],
  "keywords": ["google-analytics"]
}

**Comment by glennsl** [comment]
Thanks! The readme is quite severely inadequate though. Have a look at https://redex.github.io/publish for more information on what a good readme should, and let me know when you've addressed it :)

**Comment by viebel** [comment]
done and published

**Comment by glennsl** [comment]
Thanks!
