### ISSUE TITLE
reason-chess (please add)

### ISSUE THREAD

**Issue by venil7** [redex/data#24]
https://github.com/venil7/reason-chess

```
"reason-chess": {
  "category": "library",
  "platforms": ["any"],
  "keywords": ["game development"]
}
```

**Comment by glennsl** [comment]
Thanks! You seem to have fleshed out the readme after publishing though. Could you publish with the updated readme too?

**Comment by venil7** [comment]
oops, fixed :)

**Comment by glennsl** [comment]
Thanks!
