### ISSUE TITLE
bs-youtube

### ISSUE THREAD

**Issue by srsholmes** [redex/data#49]
"bs-youtube": {
  "category": "binding",
  "platforms": ["browser"],
  "keywords": ["ui", "video" "youtube"]
}

**Comment by glennsl** [comment]
Hey. Could you add the repository url to package.json and push a new release?

**Comment by srsholmes** [comment]
Hey, i added in the "homepage" key url, is that what was needed? 

https://github.com/srsholmes/bs-youtube/blob/master/package.json

Cheers.

**Comment by glennsl** [comment]
No, that should be inferred from the repository url if missing. I guess you had just published it before adding the repository url. Looks good now.
