### ISSUE TITLE
bs-remotedata (update to v1.0.0)

### ISSUE THREAD

**Issue by FabienHenon** [redex/data#67]
Hi,

I have an update to my package `bs-remotedata` to the version 1.0.0.

Here is the code :  
```
"bs-remotedata": {
      "category": "library",
      "platforms": ["any"],
      "keywords": ["data fetching", "utilities"]
    }
```

I don't know if it's the correct way of updating a package :(

**Comment by glennsl** [comment]
Hey. There's no need to submit update requests. As long as you've published to npm, it'll get picked up when I press the button to update redex. Which I just did.

I usually update redex when new packages are added, but it's been a while since that last one.
