### ISSUE TITLE
colors.re (Unpublished)

### ISSUE THREAD

**Issue by srsholmes** [redex/data#8]
```
"srsholmes/colors.re": {
      "repository": "github:srsholmes/colors.re",
      "category": "library",
      "platforms": ["node"],
      "keywords": ["utilities", "testing"]
}
```

**Comment by glennsl** [comment]
Cool! Why do you have the "testing" keyword though? It should probably be in "cli" instead of "utilities" too.

Also, could you use the `master` branch for your code instead? I'd rather not have to add code and configuration to support other branches if there's not a very good reason for it.

**Comment by srsholmes** [comment]
Yeah sure, i've changed the default branch to master. I put it in 'testing' because i felt people may use it to test with, and utilities as i felt it was a console utility, but i'm happy for you to change it to just "cli" 👍 

Thanks for looking at it, loving redex btw, awesome app.

**Comment by glennsl** [comment]
Thanks! I've added it, and will publish it later today.

I find most libraries can be described as utilities, unless they're more framework-like. So unless it's utility is very general I think it's better to put it in a more specific category.
